import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { css } from 'styled-system/css';
import { SiteThemeProvider } from '@/features/site-theme/providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${css({
          color: 'text',
          backgroundColor: 'base',
        })}`}
      >
        <NuqsAdapter>
          <SiteThemeProvider>{children}</SiteThemeProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
